networks:
  azki-net:
    driver: bridge

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    container_name: azki-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./infra/docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - azki-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10